version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - cart-service
      - notification-service
    environment:
      - JWT_SECRET=NAGP_SECURITY_KEY
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - CART_SERVICE_URL=http://cart-service:5004
      - NOTIFICATION_SERVICE_URL=http://notification-service:5005
    restart: always
